apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: challenge-container
          image: hsnzzzz/challenge
          resources:
            limits:
              memory: "160Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
